FROM php:7.0.6-fpm-alpine
MAINTAINER Tomaz Zaman <tomaz@codeable.io>

RUN apk add --no-cache mysql-client

RUN docker-php-ext-install -j$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) \
    iconv gd mbstring fileinfo curl xmlreader xmlwriter spl ftp mysqli

VOLUME /var/www/html
